### ISSUE TITLE
What `Delta` should I pass to `parseString`?

### ISSUE THREAD

**Issue by Gabriella439** [ekmett/trifecta#29]
The second argument of `parseString` is a `Delta`:

``` haskell
parseString :: Parser a -> Delta -> String -> Result a
```

... but I don't know what `Delta` I should pass to `parseString`.  My initial guess was `(Columns 0 0)` and that works okay, but I have no clue why or if there is a better solution that I'm missing.

Note that the reason I'm not using `parseFromFile` is that I'm writing a shell, which needs to parse interactive input.  This is the other reason why I suspect I'm doing something wrong, because the error has incorrect line information (always line 1, most likely because I'm passing in the wrong `Delta`).

**Comment by expipiplus1** [comment]
This would be good info have as a comment on `parseString`

**Comment by ekmett** [comment]
Documentation patches are always welcome.
