### ISSUE TITLE
trifecta-1.5.1.1 is broken with blaze-markup < 0.3.6

### ISSUE THREAD

**Issue by Melvar** [ekmett/trifecta#42]
In `trifecta-1.5.1.1`, `Text.Trifecta.Highlight` has restricted its import of `Text.Blaze.Internal`. However, in `blaze-markup < 0.3.6`, this is the only module that exports `preEscapedString`, so that is not in scope when building this combination of versions. Starting with `blaze-markup-0.3.6.0`, other modules including `Text.Blaze` reexport `preEscapedString`, so testing with most recent could not find this problem.

(Following the previous breakage with `blaze-markup-0.3.6`, the constraint in Idris was tightened to below this, which now results in master failing again due to this issue.)

**Comment by identicalsnowflake** [comment]
Also trying to build Idris master; same problem. I've given up trying to solve it and just built without curses.

**Comment by Melvar** [comment]
@identicalsnowflake, trifecta is required to build idris with or without curses.

**Comment by ekmett** [comment]
I'd be happy to raise the version bound or take a working patch.

I confess I'm kinda frustrated trying to mine through the blaze machinery and figure out what exactly changed when.

**Comment by Melvar** [comment]
https://github.com/ekmett/trifecta/commit/a21cf11cfa898c8dea5c2429e8b7769eb68a2dda appears to fix this. Perhaps `trifecta-1.5.1.1` should be deprecated on hackage though.
