### ISSUE TITLE
release version with 

### ISSUE THREAD

**Issue by cartazio** [ekmett/trifecta#59]
@ekmett I relaxed the bounds on reducers, and it looks like parsers needs a new release from github for an allow newer clean build of trifecta to be doable

**Comment by bgamari** [comment]
A new release would be greatly appreciated.

**Comment by jystic** [comment]
Yes please 👍

**Comment by glguy** [comment]
[trifecta-1.6](http://hackage.haskell.org/package/trifecta-1.6) is released to hackage
