### ISSUE TITLE
New release tag?

### ISSUE THREAD

**Issue by ilovezfs** [ekmett/trifecta#61]
Any chance of getting a new release tag soon? This seems to be a blocker for Idris at the moment.

**Comment by glguy** [comment]
[trifecta-1.6](http://hackage.haskell.org/package/trifecta-1.6) is released to hackage

**Comment by ilovezfs** [comment]
Awesome!!!!!

**Comment by ahmadsalim** [comment]
Thanks from the Idris developers as well!
