### ISSUE TITLE
Does `>>` or `<*` escape `<|>`?

### ISSUE THREAD

**Issue by crocket** [ekmett/trifecta#63]
I tested two statements.

```
λ> parseString ((char 'a' >> char 'b') <|> char 'c') mempty "ac"
Failure (interactive):1:2: error: expected: "b"
ac<EOF> 
 ^      
λ> parseString (try (char 'a' >> char 'b') <|> char 'c') mempty "ac"
Failure (interactive):1:1: error: expected: "c"
ac<EOF> 
^       
```

In the first statement, `char 'c'` is not even tried.
In the second, `char 'c'` is tried before failing.

It seems backtracking doesn't work properly if the first argument to `<|>` is not a single parser but a set of parsers strung by `>>` or `<*`. `try` probably turns a set of parsers into a parser.

My hypothesis is that `>>` or `<*` escapes `<|>`.

**Comment by nwf** [comment]
Given `pl <|> pr`, if `pl` consumes any input, even if it then fails, it is "committed to" and `pr` will not be tried: the definition is `Parser m <|> Parser n = Parser $ \eo ee co ce d bs -> m {- ... -} co ce d bs` -- that is, the "committed with output" and "committed with error" callbacks given to `<|>` are passed directly to the parser on the left and do not consult the parser on the right.

 `try` acts to convert the "committed with error" branch into an "epsilon with error" (i.e. an uncommitted error) branch that does not have any error information: ` try (Parser m) = Parser $ \ eo ee co _ -> m eo ee co (\_ -> ee mempty)`.

Nothing "escapes" as you are speculating, I think.

**Comment by crocket** [comment]
In `parsers`, `<|>` is not documented. It would help library users a lot to document it because it's difficult for many people to understand what's going on by reading the code.

The underlying mechanism is not trivial.

**Comment by nwf** [comment]
See #64.

**Comment by ekmett** [comment]
When you try and backtrack it'll drop any error that had consumed characters on the floor. Consequently it is almost always better to use `try whatever <?> "some description of whatever"`

e.g.

 parseString ((try (char 'a' >> char 'b') <?> "ab") <|> char 'c') mempty "ac"

Otherwise you won't get "whatever" listed in the set of alternatives you could parse at the current location.

**Comment by ekmett** [comment]
This is working as designed. trifecta follows `parsec` in that it only backtracks on non-consuming inputs. `try` treats whatever it parses as non-consuming on failure, destroying any parse errors further in, so you can replace it with "expected" token information with `(<?>)`.

**Comment by crocket** [comment]
The problem is that I couldn't find the design around `<|>` documented somewhere. I and many other users would appreciate if you shared the design of `<|>` in the form of documentation.

**Comment by ekmett** [comment]
Absolutely. In the meantime, as it stands the API for trifecta follows that of parsec in almost all things. Fortunately parsec is fairly well documented. ;)
