### ISSUE TITLE
Trifecta code triggers GHC bug when deriving instances for newtypes.

### ISSUE THREAD

**Issue by expipiplus1** [ekmett/trifecta#66]
https://ghc.haskell.org/trac/ghc/ticket/12768 is triggered by these two class methods https://github.com/ekmett/trifecta/blob/master/src/Text/Trifecta/Combinators.hs#L61 when using GND to derive an instance of `DeltaParsing`. This happens in the `hnix` package for example: https://github.com/jwiegley/hnix/issues/47

**Comment by niteria** [comment]
I've just run into this with `trifecta-1.6` and `ghc-8.0.2`. Can we blacklist `ghc-8.0.2` for `trifecta-1.6`?

**Comment by RyanGlScott** [comment]
I have no idea how you'd blacklist a Hackage release for a particular GHC version (a minor release, nonetheless), but I have uploaded [`trifecta-1.6.1`](http://hackage.haskell.org/package/trifecta-1.6.1), which does build with GHC 8.0.2.

**Comment by niteria** [comment]
Thanks for releasing `trifecta-1.6.1`. I was unfortunate enough to try stackage `lts-7.10` with GHC 8.0.2 which has `trifecta-1.6`. `lts-7.11` has `trifecta-1.6.1`.

I think blacklisting GHC 8.0.2 is just a matter of editing the bound in hackage to say `ghc < 8.0.2 || > 8.0.2`, but I might be completely wrong.

**Comment by RyanGlScott** [comment]
I'm loathe to edit in `ghc < 8.0.2 || > 8.0.2` in the `build-depends`, as that would mean that `trifecta` would begin to link against the `ghc` library itself, which forces you to use particular versions of some dependencies (`binary`, `containers`, `deepseq`, `pretty`, etc.).

@hvr, is there a way to do this without linking against `ghc` itself?

**Comment by niteria** [comment]
It's not a big deal, so if it's hard to do, I don't mind it staying the way it is.

**Comment by ekmett** [comment]
We can just use `ghc < 8.0.2`.

**Comment by RyanGlScott** [comment]
Oh! Do you mean editing in

```
if impl(ghc >= 8.0.2)
  buildable: False
```

into the `trifecta.cabal` of old releases on Hackage? That just might work...

**Comment by ekmett** [comment]
That'd work. It'd need someone like @hvr to do it though.

-Edward

**Comment by RyanGlScott** [comment]
> It'd need someone like @hvr to do it though.

Indeed. I tried adding it myself, but was greeted with this error message:

> Cannot publish new revision
> 
> ### Errors
> 
> Cannot add or remove 'if' conditionals

**Comment by hvr** [comment]
while it isn't the ideal, why not abuse `base`'s version as proxy here? I.e. set `base < 4.9.1`

**Comment by RyanGlScott** [comment]
Heh, I had forgotten that there was a minor version bump for `base` in this upcoming GHC release. Given the lack of alternatives, I've chosen to do just what you've suggested in http://hackage.haskell.org/package/trifecta-1.6/revisions/.

**Comment by ekmett** [comment]
That works perfectly

**Comment by niteria** [comment]
Thank you! Much appreciated.
