### ISSUE TITLE
New release for the sake of GHC 8.0.2?

### ISSUE THREAD

**Issue by ilovezfs** [ekmett/trifecta#68]
It would be great to have a new release of trifecta on Hackage since currently all its reverse dependencies like Idris are dead-in-the-water without patching if GHC 8.0.2 is used.

**Comment by RyanGlScott** [comment]
[`trifecta-1.6.1`](http://hackage.haskell.org/package/trifecta-1.6.1), which supports GHC 8.0.2, has been uploaded to Hackage.

**Comment by ilovezfs** [comment]
@RyanGlScott Thanks!!!
