### ISSUE TITLE
Add example of nice-looking error messages

### ISSUE THREAD

**Issue by chshersh** [ekmett/trifecta#77]
It's stated in the documentation for `triffecta` package that it has _Clang-style colored diagnostics_. But I can't find viewable example of this diagnostics. It would be really great to add screenshot of nice-looking errors in the README or directly to Hackage documentation.

**Comment by ekmett** [comment]
I added at least one finally. =)

**Comment by chshersh** [comment]
@ekmett Thanks! The error messages indeed look nice :slightly_smiling_face:
