### ISSUE TITLE
Slow compile times, remove INLINE on satisfy?

### ISSUE THREAD

**Issue by andrevdm** [ekmett/trifecta#80]
I'm getting slow compile times on a fairly small parser when I use a number of `choice` combinators. It is averaging around 30 seconds for my parser module.

If I enable `-ddump-timings`, I can see the dominant factor is the simplifier

```
1013 - Simplifier [Main]: alloc=1068672688 time=1013.738
1577 - Simplifier [Main]: alloc=1353713200 time=1577.066
1687 - Simplifier [Main]: alloc=1651513384 time=1687.849
1697 - Simplifier [Main]: alloc=1619116360 time=1697.374
1970 - Simplifier [Main]: alloc=1960801872 time=1970.856
2022 - Simplifier [Main]: alloc=1865558352 time=2022.854
```

If I build with a fork of trifecta I can half the compile time by removing the `INLINE` pragma on 
`satisfy` for `instance CharParsing Parser` in `Text.Trifecta.Parser`. (I can't find any other INLINES that have similar impact)

Is this expected behaviour, or should the INLINE be removed?

Compiling with `-O0` fixes the issue for development, but 30 second compile times did surprise me.

It's quite easy to replicate, something like this should do it

```
import qualified Text.Trifecta as T

start :: T.Parser String
start = 
  T.choice [ T.integer <&> show
           , T.integer <&> show
           , T.integer <&> show
           , T.integer <&> show
```

Adding more `T.integer <&> show` lines give you a roughly linear slow down. (On my machine ~150ms per line and my test has about 150 of them in total).

Thanks!

**Comment by phadej** [comment]
https://ghc.haskell.org/trac/ghc/ticket/13253

**Comment by andrevdm** [comment]
Do you think that is the same issue? 

That seems to mention `<*>`. Removing INLINE on Trifecta's `<*>` did not seem to make a big difference for me.

(I'm entirely in the dark on this though, so I may be misreading that ticket)

**Comment by andrevdm** [comment]
I've looked again, if you think that is an existing ticket for the simplifier in general I'll be happy to close this issue.

**Comment by phadej** [comment]
Let's keep this ticket open until GHC issue is solved, than we can check whether the `trifecta`'s compilation time is improved.

**Comment by ekmett** [comment]
Switched to INLINABLE everywhere in HEAD. Can you see if that helps you?

**Comment by ekmett** [comment]
Please re-open if not.
