### ISSUE TITLE
Result should be an instance of Eq to allow for testing

### ISSUE THREAD

**Issue by vaibhav-y** [ekmett/trifecta#81]
https://github.com/ekmett/trifecta/blob/16e065c6f157c1dbd70312fe27bf958291b7cc26/src/Text/Trifecta/Result.hs#L116-L119

Currently it is not possible to use `Text.Trifecta.Result` in a test-case for directly for comparison because it doesn't derive from `Eq`. `Result` should also derive from `Eq` so that there can be tests for parsers written with trifecta.

Workarounds known for this:
* Unpack `Result` and compare the wrapped contents as necessary

**Comment by vaibhav-y** [comment]
@ekmett Any thoughts?

**Comment by ekmett** [comment]
`ErrInfo` isn't an instance of `Eq`, which blocks this.
