### ISSUE TITLE
Show line numbers in rendered Span

### ISSUE THREAD

**Issue by robrix** [ekmett/trifecta#82]
`ghc` has a feature where its error messages often show the line numbers as prefixes on source lines:

<img width="329" alt="screen shot 2018-12-19 at 9 08 33 am" src="https://user-images.githubusercontent.com/59671/50225164-bedd3f00-036d-11e9-9c43-de4a7cce367a.png">

I’d love to have the same for trifecta’s rendering of `Span`s, especially given the (very nice!) feature where spans on long lines show only the relevant portion of the line.

I think this should be possible due to the inclusion of the `Delta`s in `Span`s, so if you’d be willing to review a PR with this, I’ll give it a try myself 👍

**Comment by phadej** [comment]
Please go ahead!

**Comment by robrix** [comment]
@phadej: I experimented with this tonight a bit, and I think the right way to go about this is in the `Pretty` instance for `Rendering`. One thing I wasn’t clear on is whether renderings ever contain multiple lines from the source text, or only one line of source + the caret/span/fixit markers. This ends up mattering because we only have a `Delta` for the start, and calculating the width of the gutter for the first line might not be sufficient if there are more lines of source.

I wasn’t able to construct a multiple-source-line `Rendering` in my experiments thus far, but I can’t rule them out either; do you happen to know if it really is capped at one?
