### ISSUE TITLE
Stuck on left recursive grammar

### ISSUE THREAD

**Issue by pzzp** [ekmett/trifecta#86]
code:
```
data Expr
    = Apply Expr Expr
    | Lambda Char Expr
    | Name Char
    deriving (Show)

parseExpr:: Parser Expr
parseExpr = parseApply <|> parseLambda <|> parseName where
    parseApply = do
        f <- parseExpr
        _ <- spaces
        g <- parseExpr
        pure $ Apply f g
    parseLambda = do
        _ <- char '\\'
        v <- anyChar
        _ <- char '.'
        e <- parseExpr
        pure $ Lambda v e
    parseName = Name <$> anyChar

main :: IO ()
main = print $ parseString parseExpr mempty "a"
```

**Comment by phadej** [comment]
This is common limitation of monadic parsers, like parsec, megaoarsec or trifecta. You’d need to use `many` or similar combinator: 
https://stackoverflow.com/questions/47475486/parsing-left-recursive-grammar-in-sum-type-inifinite-recursion

**Comment by pzzp** [comment]
> This is common limitation of monadic parsers, like parsec, megaoarsec or trifecta. You’d need to use `many` or similar combinator: https://stackoverflow.com/questions/47475486/parsing-left-recursive-grammar-in-sum-type-inifinite-recursion
> […](#)
> On 10 Nov 2019, at 10.21, pzzp ***@***.***> wrote: code: data Expr = Apply Expr Expr | Lambda Char Expr | Name Char deriving (Show) parseExpr:: Parser Expr parseExpr = parseApply <|> parseLambda <|> parseName where parseApply = do f <- parseExpr _ <- spaces g <- parseExpr pure $ Apply f g parseLambda = do _ <- char '\\' v <- anyChar _ <- char '.' e <- parseExpr pure $ Lambda v e parseName = Name <$> anyChar main :: IO () main = print $ parseString parseExpr mempty "a" — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I see, thank you
